const DELTA = '~';
const MULTIPLICATION = 'x';
const NUM_DELIMITER = ',';
const DELTA_LIST_BY_ONE = '.';
const DELTA_LIST_BY_TWO = ':';
const ZIP_START_DELIMITER = '(';
const ZIP_END_DELIMITER = ')';
const MODE_SIMPLE_STRING = 1;
const MODE_DELTA_STRING = 2;

module.exports = {
  DELTA,
  MULTIPLICATION,
  NUM_DELIMITER,
  DELTA_LIST_BY_ONE,
  DELTA_LIST_BY_TWO,
  ZIP_START_DELIMITER,
  ZIP_END_DELIMITER,
  MODE_SIMPLE_STRING,
  MODE_DELTA_STRING,
};
